### PR TITLE
Fix rendering of menu controls in the admin UI

### PR DESCRIPTION
**Pull request by vbessonov**
## Description

This PR fixes the rendering of menu controls in the admin UI. Menu controls with multiple selected values are currently rendered like that:
image

@tdilauro, this PR should allow you to test [PR # 1554](https://github.com/NYPL-Simplified/circulation/pull/1554).

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by leonardr** [comment]
@adriana-alter Does this make sense to you?

**Comment by adriana-alter** [comment]
It definitely makes sense, but is the list of SAML attributes the only use case?  If so, I'd rather see it called something other than `menu`, just to be sure that nothing is conflicting with the existing `menu` functionality.

**Comment by leonardr** [comment]
@vbessonov What's the difference between the list of SAML attributes and some other `menu` type configuration setting? Or is the new behavior an improvement for all `menu` type settings?

**Review by tdilauro — APPROVED** [review]
This change does resolve the issues that I was experiencing.

I'm approving now, pending feedback from @leonardr and @adriana-alter.

**Comment by vbessonov** [comment]
@leonardr, yes, my changes should suit any `menu` controls. I used SAML configuration settings as an example but I think I can make a more generic example.

**Comment by leonardr** [comment]
I'm OK with merging on the basis that this will improve things for all `menu` type attributes -- do you want to complete the more generic example in this branch or leave it til later?

**Comment by vbessonov** [comment]
Since it's blocking [PR # 1554](https://github.com/NYPL-Simplified/circulation/pull/1554) which is pretty critical I would prefer to merge it as is and later I'll add a more generic example.

**Comment by leonardr** [comment]
OK, sounds good.

**Pull request merged**
