### PR TITLE
Made Lane constructor take db argument.

### PR DESCRIPTION
**Pull request by aslagle**
This goes with https://github.com/NYPL-Simplified/server_core/pull/560.

Having Lane._db come from the Library was causing a scoped session error when creating CachedFeeds, so Leonard suggested passing the db to the Lane constructor.

I'm not sure how to write a test for the problem I was seeing, but I verified that this fixed it. It happened when going to the root url and getting redirected after you'd already been to /groups.

### CODE REVIEW

**Comment by leonardr** [comment]
:+1: 

If you want to test this, use `TestScopedSession.test_scoped_session` as a model. Maybe modify that method to call self.manager.index_controller() within its scoped request after checking that it gets its own database session.

**Comment by aslagle** [comment]
I added a test, but it doesn't fail with the old code.

**Comment by leonardr** [comment]
That's strange, but I do think there's a class of errors that this test will catch, so let's keep it.

**Comment by aslagle** [comment]
I think this will have to do. The controller that gets the error works fine in a test, maybe because the transaction from previous requests aren't committed.

**Pull request merged**
